name: router_animation
description: Animated page transition
version: 0.0.2
environment:
  sdk: '>=2.0.0-dev.42.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+8
  angular_router: ^2.0.0-alpha+8
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+2
