name: router_animation
description: Animated page transition
version: 0.0.3
environment:
  sdk: '>=2.0.0-dev.48.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+10
  angular_router: ^2.0.0-alpha+10
dev_dependencies:
  build_runner: ^0.8.2
  build_web_compilers: ^0.3.6
